// Note that this file is not actually medium zoom, it is generated by OpenAI Chat GPT

const zoomableElements = document.querySelectorAll('img');

zoomableElements.forEach(element => {
  element.addEventListener('click', () => {
    element.classList.toggle('zoomed');

    if (element.classList.contains('zoomed')) {
      if (element.classList.contains('zoomed').width/element.classList.contains('zoomed').height > 16/9) {
        element.style.width = '100vw';
        element.style.height = 'auto';
        element.style.position = 'fixed';
        element.style.top = '0';
        element.style.left = '0';
        element.style.zIndex = '999';
      }
      else {
        element.style.width = 'auto';
        element.style.height = '100vh';
        element.style.position = 'fixed';
        element.style.top = '0';
        element.style.left = '0';
        element.style.zIndex = '999';
      }
    } else {
      element.style.width = '100%';
      element.style.height = '100%';
      element.style.position = '';
      element.style.top = '';
      element.style.left = '';
      element.style.zIndex = '';
    }
  });
});

document.addEventListener('scroll', () => {
  zoomableElements.forEach(element => {
    element.classList.remove('zoomed');
    element.style.width = '';
    element.style.position = '';
    element.style.top = '';
    element.style.left = '';
    element.style.zIndex = '';
  });
});
